### ISSUE TITLE
Specification rate limiting

### ISSUE THREAD

**Issue by jnehring** [freme-project/technical-discussion#91]
We want to rate-limit the usage of FREME API. This issue should specify a feature set for rate limiting. My suggestions for the first version

* We define a time span and different limits. So e.g. each user is allowed to do either 10 API calls or process 1000 kb of text in a time span of 10 minutes.
* We make these limits configurable via the configuration file.
* When a user reaches the rate limit then all API calls are aborted and the API returns HTTP Status 429 (Too many requests) + appropriate error message.
* Anonymous / not authenticated users are identified via their IP address.
* Authenticated and anonymous users have the same rate limits in the first version.
* We need the possibility to override the limits for certain endpoints, e.g. for dataset upload.
* We need the possibility to override the limits for certain users.
* There should be a configuration option "freme.ratelimit.enable" with a default value of true. Setting it to false disables rate limiting.

The idea of overriding needs more thoughts how to configure it as easy as possible.

@josauder what do you think about this?

**Comment by jnehring** [comment]
Configuration of rate limiting in file "rate-limiting-config.yml"
```
time-period: 600    # time period in seconds
rate-limits:
  anonymous: 
    default: [50, 1000] # anomyous user has 50 requests or 1000 kb in the time period
    /freme-ner/datasets: [50, 1000000]: # override for anonymous user to allow 50 requests or 1000 mb in the time period
  authenticated:
    default: [50, 1000] # anomyous user has 50 requests or 1000 kb in the time period
    /freme-ner/datasets: [50, 2000000]: # override for authenticated users to allow 50 requests or 2000 mb in the time period
  admin:
    default: [0, 0]  # admin user has no rate limits configured
  henry: 
    /e-translation/tilde: [50, 10000] # user henry has a special override on tilde
```
